#!/bin/bash

#! Name of the job:
#SBATCH -J  GEMMA_ASSOC
#! Which project should be charged:
#SBATCH -A ESANTOS-SL3-CPU
#SBATCH -p icelake
#! How many whole nodes should be allocated?
#SBATCH --nodes=1
#! How many (MPI) tasks will there be in total? (<= nodes*76)
#! The Ice Lake (icelake) nodes have 76 CPUs (cores) each and
#! 3380 MiB of memory per CPU.
#SBATCH --ntasks=8
#! How much wallclock time will be required?
#SBATCH --time=2:00:00
#! What types of email messages do you wish to receive?
#SBATCH --mail-type=NONE
#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue
workdir="$SLURM_SUBMIT_DIR"

. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel8/default-icl              # REQUIRED - loads the basic environment

# Activate Conda
source ~/miniconda3/bin/activate          # Update this if the path differs
conda activate GEMMA                      # Activate the GEMMA environment

#gemma uses phenotype by default (the sixth column of .fam file) if not specified explicitly
# Running GEMMA for GWAS with covariates and a minimum MAF filter
gemma -bfile ../Masoko_SUBSET_FILTERED_for_THEIS_pheno \
      -k ../output/Masoko_SUBSET_FILTERED_for_THEIS_pheno.cXX.txt \
      -c Only_Sl.txt \
      -maf 0.05 \
      -lmm 4 \
      -o Masoko_GWAS_with_covariates_SL_covar

conda deactivate



date